version: 2.1

orbs:
  slack: circleci/slack@3.4.2

references:
  install_dockerize: &install_dockerize
    run:
      name: install dockerize
      command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
      environment:
        DOCKERIZE_VERSION: v0.6.1

jobs:
  # dockerのビルドテスト
  build-docker:
    machine:
      image: ubuntu-1604:201903-01
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: build
          command: |
            make build
      - run:
          name: up services
          command: |
            docker-compose up -d
      - run:
          name: Wait for db
          command: |
            ./.circleci/wait-for-mysql.sh db 3306 root password
      - run:
          name: init db
          command: |
            make migrate
      - run:
          name: Unit Test
          command: |
            make test
      - run:
          name: lint
          command: |
            make format-dry-run
      - slack/status:
          success_message: '$CIRCLE_BRANCH ブランチ dockerのビルドに成功しました\n User：$CIRCLE_USERNAME'
          failure_message: '$CIRCLE_BRANCH ブランチ dockerのビルドに失敗しました\n User：$CIRCLE_USERNAME'

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build-docker:
          filters:
            branches:
              only:
                - develop
                - /^feature.*/
